### ISSUE TITLE
AttributeError: 'cython_function_or_method' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Fusl** [ArchiveTeam/ludios_wpull#16]
```
grab-site --import-ignores /data/ignores --no-offsite-links "https://sec.gov" "https://www.sec.gov/"
```

```
[...]
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001452835&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001433865&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001737697&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001320420&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001632015&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001741019&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetvu2.htm ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001727436&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetve2.htm ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001741028&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/ice2015123110k.htm ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&State=GA&owner=exclude&match=&start=40&count=40&hidefilings=0 ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetvv2.htm ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/ice-20151231.xml ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetve2_all.jpg ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetvu5.htm ...
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&SIC=6141&owner=exclude&count=40&hidefilings=0 ...
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetve3_all.jpg ...
ERROR Fatal exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/wpull/application/app.py", line 157, in run
    yield from pipeline.process()
  File "/usr/local/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/usr/local/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/usr/local/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/usr/local/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/usr/local/lib/python3.7/site-packages/wpull/application/tasks/download.py", line 421, in process
    yield from session.app_session.factory['Processor'].process(session)
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/delegate.py", line 29, in process
    return (yield from processor.process(item_session))
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/web.py", line 91, in process
    return (yield from session.process())
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/web.py", line 185, in process
    yield from self._process_loop()
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/web.py", line 244, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(cast(Request, self._item_session.request))
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/web.py", line 308, in _fetch_one
    action = self._handle_response(request, response)
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/web.py", line 423, in _handle_response
    self._processing_rule.scrape_document(self._item_session)
  File "/usr/local/lib/python3.7/site-packages/libgrabsite/wpull_tweaks.py", line 55, in scrape_document
    super().scrape_document(item_session)
  File "/usr/local/lib/python3.7/site-packages/wpull/processor/rule.py", line 527, in scrape_document
    item_session.url_record.link_type
  File "/usr/local/lib/python3.7/site-packages/wpull/scraper/base.py", line 186, in scrape_info
    scrape_result = scraper.scrape(request, response, link_type)
  File "/usr/local/lib/python3.7/site-packages/wpull/scraper/html.py", line 114, in scrape
    elements, response, base_url, link_contexts
  File "/usr/local/lib/python3.7/site-packages/wpull/scraper/html.py", line 176, in _process_elements
    if not self._is_accepted(link_info.tag):
  File "/usr/local/lib/python3.7/site-packages/wpull/scraper/html.py", line 257, in _is_accepted
    element_tag = element_tag.lower()
AttributeError: 'cython_function_or_method' object has no attribute 'lower'
CRITICAL Sorry, Wpull unexpectedly crashed.
https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetvf3.htm ...

DUPE https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&filenum=333-183086&owner=include&start=0&count=40
  OF https://www.sec.gov/cgi-bin/browse-edgar?company=&match=&filenum=333-183086&State=&Country=&SIC=&myowner=exclude&action=getcompany
DUPE https://www.sec.gov/Archives/edgar/data/1554157/000116552712001007/0001165527-12-001007-index.htm
  OF https://www.sec.gov/Archives/edgar/data/1554157/000116552712001007/0001165527-12-001007-index.htm
DUPE https://www.sec.gov/Archives/edgar/data/1554157/000151116413000329/0001511164-13-000329-index.htm
  OF https://www.sec.gov/Archives/edgar/data/1554157/000151116413000329/0001511164-13-000329-index.htm
DUPE https://www.sec.gov/Archives/edgar/data/1554157/000116552712001090/0001165527-12-001090-index.htm
  OF https://www.sec.gov/Archives/edgar/data/1554157/000116552712001090/0001165527-12-001090-index.htm
DUPE https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&filenum=333-183086&owner=include&count=40
  OF https://www.sec.gov/cgi-bin/browse-edgar?company=&match=&filenum=333-183086&State=&Country=&SIC=&myowner=exclude&action=getcompany
DUPE https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001554157&type=&dateb=&owner=include&count=100&output=xml
  OF https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&filenum=333-183086&type=&dateb=&owner=include&count=100&output=xml
DUPE https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001554157&type=&dateb=&owner=include&start=0&count=40&output=atom
  OF https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001554157&type=&dateb=&owner=include&count=40&output=atom
DUPE https://www.sec.gov/cgi-bin/goodbye.cgi?www.regulations.gov
  OF https://www.sec.gov/cgi-bin/goodbye.cgi?www.regulations.gov
DUPE https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&State=GA&owner=exclude&count=40&hidefilings=0
  OF https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&State=GA&owner=exclude&count=40
DUPE https://www.sec.gov/Archives/edgar/data/1658496/000165849616000008/icetve3_all.jpg
  OF https://www.sec.gov/Archives/edgar/data/1658496/000165849617000009/icetve3_all.jpg
Event loop is closed
Exception ignored in: <coroutine object sender at 0x7fa76b6fc848>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/libgrabsite/dashboard_client.py", line 54, in sender
    await asyncio.sleep(delay)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 566, in sleep
    future, result)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 657, in call_later
    context=context)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 667, in call_at
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Disconnected from ws:// server: RuntimeError('Event loop is closed')
```

**Comment by ivan** [comment]
Please let me know if you see this again or know exactly which page causes the crash, that would make it easier to test here.

**Comment by tempname1024** [comment]
> Please let me know if you see this again or know exactly which page causes the crash, that would make it easier to test here.

I ran into a similar issue, reported here https://github.com/ArchiveTeam/grab-site/issues/173.

**Comment by mozillamonks** [comment]
A long time come back to this issue, but this can reproducible recreate this error:
grab-site http://foxstripcomics.comicgenesis.com

**Comment by ivan** [comment]
Thanks. grab-site 2.2.2 should no longer be crashing on http://foxstripcomics.comicgenesis.com, though unfortunately the page is very broken and grab-site fails to extract links from it.

![Screenshot 2021-08-29 023225](https://user-images.githubusercontent.com/4458/131238806-09792b37-517b-4ab0-a0bc-2c9af0dd2dd2.png)
